
POST http://localhost:3000/patientAuth/login
Content-Type: application/json

{
    "userId":"jemimah.vidal",
    "password":"password"
}

###

POST http://localhost:3000/patientAuth/signup
Content-Type: application/json

{
    "userId":"jemimah.vidal",
    "password":"password",
    "patient":"62ce5a06622650592486469d"

}

###
GET http://localhost:3000/patientAuth/62ce629d62265059248646ad

###
DELETE http://localhost:3000/patientAuth/62ce629d62265059248646ad

###
PATCH http://localhost:3000/patientAuth/62ce629d62265059248646ad
Content-Type: application/json

{
    "userId":"Jon Snow"
}
